version: '3.9'
services:
  postgresdb:
    image: postgres:latest
    container_name: currency-conversion
    volumes:
      - database_postgres:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    restart: always
    networks:
      - currency-conversion
  app:
    container_name: currency-conversion-service
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - currency-conversion
    ports:
      - "8080:8080"
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - postgresdb
volumes:
  api:
  database_postgres:

networks:
   currency-conversion:
     driver: bridge