version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: currency-conversion
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=currency-conversion
