// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mehmetokdemir/currency-conversion-service/internal/exchange (interfaces: IExchangeService)

// Package exchange is a generated GoMock package.
package exchange

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	account "github.com/mehmetokdemir/currency-conversion-service/internal/account"
)

// MockIExchangeService is a mock of IExchangeService interface.
type MockIExchangeService struct {
	ctrl     *gomock.Controller
	recorder *MockIExchangeServiceMockRecorder
}

// MockIExchangeServiceMockRecorder is the mock recorder for MockIExchangeService.
type MockIExchangeServiceMockRecorder struct {
	mock *MockIExchangeService
}

// NewMockIExchangeService creates a new mock instance.
func NewMockIExchangeService(ctrl *gomock.Controller) *MockIExchangeService {
	mock := &MockIExchangeService{ctrl: ctrl}
	mock.recorder = &MockIExchangeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIExchangeService) EXPECT() *MockIExchangeServiceMockRecorder {
	return m.recorder
}

// AcceptExchangeRateOffer mocks base method.
func (m *MockIExchangeService) AcceptExchangeRateOffer(arg0 uint, arg1 AcceptOfferRequest) ([]account.WalletAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptExchangeRateOffer", arg0, arg1)
	ret0, _ := ret[0].([]account.WalletAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcceptExchangeRateOffer indicates an expected call of AcceptExchangeRateOffer.
func (mr *MockIExchangeServiceMockRecorder) AcceptExchangeRateOffer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptExchangeRateOffer", reflect.TypeOf((*MockIExchangeService)(nil).AcceptExchangeRateOffer), arg0, arg1)
}

// GetExchangeRateOffer mocks base method.
func (m *MockIExchangeService) GetExchangeRateOffer(arg0 uint, arg1 OfferRequest) (*OfferResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExchangeRateOffer", arg0, arg1)
	ret0, _ := ret[0].(*OfferResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExchangeRateOffer indicates an expected call of GetExchangeRateOffer.
func (mr *MockIExchangeServiceMockRecorder) GetExchangeRateOffer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExchangeRateOffer", reflect.TypeOf((*MockIExchangeService)(nil).GetExchangeRateOffer), arg0, arg1)
}
