// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mehmetokdemir/currency-conversion-service/internal/account (interfaces: IAccountRepository)

// Package account is a generated GoMock package.
package account

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIAccountRepository is a mock of IAccountRepository interface.
type MockIAccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIAccountRepositoryMockRecorder
}

// MockIAccountRepositoryMockRecorder is the mock recorder for MockIAccountRepository.
type MockIAccountRepositoryMockRecorder struct {
	mock *MockIAccountRepository
}

// NewMockIAccountRepository creates a new mock instance.
func NewMockIAccountRepository(ctrl *gomock.Controller) *MockIAccountRepository {
	mock := &MockIAccountRepository{ctrl: ctrl}
	mock.recorder = &MockIAccountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAccountRepository) EXPECT() *MockIAccountRepositoryMockRecorder {
	return m.recorder
}

// CreateAccount mocks base method.
func (m *MockIAccountRepository) CreateAccount(arg0 Account) (*Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", arg0)
	ret0, _ := ret[0].(*Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockIAccountRepositoryMockRecorder) CreateAccount(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockIAccountRepository)(nil).CreateAccount), arg0)
}

// GetUserBalanceOnGivenCurrencyAccount mocks base method.
func (m *MockIAccountRepository) GetUserBalanceOnGivenCurrencyAccount(arg0 uint, arg1 string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBalanceOnGivenCurrencyAccount", arg0, arg1)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserBalanceOnGivenCurrencyAccount indicates an expected call of GetUserBalanceOnGivenCurrencyAccount.
func (mr *MockIAccountRepositoryMockRecorder) GetUserBalanceOnGivenCurrencyAccount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBalanceOnGivenCurrencyAccount", reflect.TypeOf((*MockIAccountRepository)(nil).GetUserBalanceOnGivenCurrencyAccount), arg0, arg1)
}

// IsUserHasAccountOnGivenCurrency mocks base method.
func (m *MockIAccountRepository) IsUserHasAccountOnGivenCurrency(arg0 uint, arg1 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserHasAccountOnGivenCurrency", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsUserHasAccountOnGivenCurrency indicates an expected call of IsUserHasAccountOnGivenCurrency.
func (mr *MockIAccountRepositoryMockRecorder) IsUserHasAccountOnGivenCurrency(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserHasAccountOnGivenCurrency", reflect.TypeOf((*MockIAccountRepository)(nil).IsUserHasAccountOnGivenCurrency), arg0, arg1)
}

// ListUserAccounts mocks base method.
func (m *MockIAccountRepository) ListUserAccounts(arg0 uint) ([]Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserAccounts", arg0)
	ret0, _ := ret[0].([]Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserAccounts indicates an expected call of ListUserAccounts.
func (mr *MockIAccountRepositoryMockRecorder) ListUserAccounts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserAccounts", reflect.TypeOf((*MockIAccountRepository)(nil).ListUserAccounts), arg0)
}

// Migration mocks base method.
func (m *MockIAccountRepository) Migration() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Migration")
	ret0, _ := ret[0].(error)
	return ret0
}

// Migration indicates an expected call of Migration.
func (mr *MockIAccountRepositoryMockRecorder) Migration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Migration", reflect.TypeOf((*MockIAccountRepository)(nil).Migration))
}

// UpdateUserBalanceOnGivenCurrencyAccount mocks base method.
func (m *MockIAccountRepository) UpdateUserBalanceOnGivenCurrencyAccount(arg0 uint, arg1 string, arg2 float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserBalanceOnGivenCurrencyAccount", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserBalanceOnGivenCurrencyAccount indicates an expected call of UpdateUserBalanceOnGivenCurrencyAccount.
func (mr *MockIAccountRepositoryMockRecorder) UpdateUserBalanceOnGivenCurrencyAccount(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserBalanceOnGivenCurrencyAccount", reflect.TypeOf((*MockIAccountRepository)(nil).UpdateUserBalanceOnGivenCurrencyAccount), arg0, arg1, arg2)
}
